[2024-11-06T10:50:34.977+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T10:50:34.997+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.store_user manual__2024-11-06T10:50:20.501686+00:00 [queued]>
[2024-11-06T10:50:35.007+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.store_user manual__2024-11-06T10:50:20.501686+00:00 [queued]>
[2024-11-06T10:50:35.008+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-06T10:50:35.022+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): store_user> on 2024-11-06 10:50:20.501686+00:00
[2024-11-06T10:50:35.036+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-06T10:50:35.038+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2024-11-06T10:50:35.039+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2024-11-06T10:50:20.501686+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/user-processing.py', '--cfg-path', '/tmp/tmpw7xvtqzy']
[2024-11-06T10:50:35.042+0000] {standard_task_runner.py:105} INFO - Job 84: Subtask store_user
[2024-11-06T10:50:35.542+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.store_user manual__2024-11-06T10:50:20.501686+00:00 [running]> on host a664c8dd9839
[2024-11-06T10:50:35.623+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='store_user' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T10:50:20.501686+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T10:50:20.501686+00:00'
[2024-11-06T10:50:35.625+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T10:50:35.638+0000] {postgres.py:191} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2024-11-06T10:50:35.648+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2024-11-06T10:50:35.656+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-06T10:50:35.670+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T10:50:35.671+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, run_id=manual__2024-11-06T10:50:20.501686+00:00, execution_date=20241106T105020, start_date=20241106T105034, end_date=20241106T105035
[2024-11-06T10:50:35.735+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-06T10:50:35.957+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T10:50:35.959+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
