[2024-11-06T16:25:54.471+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T16:25:54.493+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parent_dag_for_taskgroup.check_files manual__2024-11-06T16:25:34.571239+00:00 [queued]>
[2024-11-06T16:25:54.505+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parent_dag_for_taskgroup.check_files manual__2024-11-06T16:25:34.571239+00:00 [queued]>
[2024-11-06T16:25:54.506+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-06T16:25:54.525+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): check_files> on 2024-11-06 16:25:34.571239+00:00
[2024-11-06T16:25:54.531+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=331) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-06T16:25:54.533+0000] {standard_task_runner.py:72} INFO - Started process 332 to run task
[2024-11-06T16:25:54.533+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parent_dag_for_taskgroup', 'check_files', 'manual__2024-11-06T16:25:34.571239+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/parent_dag_for_taskgroups.py', '--cfg-path', '/tmp/tmp6bpxz8fk']
[2024-11-06T16:25:54.534+0000] {standard_task_runner.py:105} INFO - Job 122: Subtask check_files
[2024-11-06T16:25:54.588+0000] {task_command.py:467} INFO - Running <TaskInstance: parent_dag_for_taskgroup.check_files manual__2024-11-06T16:25:34.571239+00:00 [running]> on host 66acfa37dd15
[2024-11-06T16:25:54.675+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parent_dag_for_taskgroup' AIRFLOW_CTX_TASK_ID='check_files' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T16:25:34.571239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T16:25:34.571239+00:00'
[2024-11-06T16:25:54.676+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T16:25:54.690+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-06T16:25:54.692+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 10']
[2024-11-06T16:25:54.701+0000] {subprocess.py:86} INFO - Output:
[2024-11-06T16:26:04.703+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-06T16:26:04.737+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T16:26:04.738+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=parent_dag_for_taskgroup, task_id=check_files, run_id=manual__2024-11-06T16:25:34.571239+00:00, execution_date=20241106T162534, start_date=20241106T162554, end_date=20241106T162604
[2024-11-06T16:26:04.805+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-06T16:26:04.829+0000] {taskinstance.py:3900} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-11-06T16:26:04.833+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
